site_name: Portal Datazonia
repo_url: https://github.com/unb-mds/2024-2-Squad10

nav:
  - Home: index.md
  - Arquitetura: arquitetura.md
  - Story Map: storymap.md
  - Prot√≥tipo: prototipo.md
  - Sprints:
    - Sprint 0: sprints/sprint0.md
    - Sprint 1: sprints/sprint1.md
    - Sprint 2: sprints/sprint2.md
    - Sprint 3: sprints/sprint3.md
    - Sprint 4: sprints/sprint4.md
    - Sprint 5: sprints/sprint5.md
    - Sprint 6: sprints/sprint6.md
    - Sprint 7: sprints/sprint7.md
    - Sprint 8: sprints/sprint8.md

theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "indigo"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features: 
    -navigation.tabs